[package]
name = "feretto"
version = "0.0.2"
authors = ["Joseph Kordish <joe@unicornclouds.com>"]

description = "Utility to generate consul events from matched strings found in a file/log"
homepage = "https://github.com/jkordish/feretto"
repository = "https://github.com/jkordish/feretto"

readme = "README.md"
license = "The MIT License (MIT)"

keywords = [
  "consul",
  "event",
  "notify",
  "logs"
]

[dependencies]
docopt = "^0.6.81"
docopt_macros = "^0.6.84"
rustc-serialize = "^0.3.19"
curl = "^0.2.19"
notify = "^2.6.1"
aho-corasick = "^0.5.2"
serde = "^0.7.11"
serde_json = "^0.7.2"
serde_macros = "^0.7.11"
crossbeam = "^0.2.9"
clippy = {version="^0.0.77", optional = true}

[features]
default=[]
