[package]
name = "feretto"
version = "0.0.2"
authors = ["Joseph Kordish <joe@unicornclouds.com>"]

description = "Utility to generate consul events from matched strings found in a file/log"
homepage = "https://github.com/jkordish/feretto"
repository = "https://github.com/jkordish/feretto"

readme = "README.md"
license = "The MIT License (MIT)"

keywords = [
  "consul",
  "event",
  "notify",
  "logs"
]

[dependencies]
docopt = "^0.6.78"
docopt_macros = "^0.6.82"
rustc-serialize = "^0.3.18"
curl = "^0.2.18"
notify = "^2.5.5"
aho-corasick = "^0.5.1"
serde = "^0.7.0"
serde_json = "^0.7.0"
serde_macros = "^0.7.0"
crossbeam = "^0.2.8"
clippy = {version="^0.0.60", optional = true}

[features]
default=[]
